### ISSUE TITLE
Exception: Couldn't load com_couchbase_touchdb_TDCollateJSON from loader

### ISSUE THREAD

**Issue by mitaichik** [couchbase/couchbase-lite-android-liteserv#25]
Hello ! I have more12 000 exceptions like 

java.lang.UnsatisfiedLinkError: Couldn't load com_couchbase_touchdb_TDCollateJSON from loader dalvik.system.PathClassLoader....

form different devices and android version.

Stacktrace:

java.lang.UnsatisfiedLinkError: Couldn't load com_couchbase_touchdb_TDCollateJSON from loader dalvik.system.PathClassLoader[dexPath=/data/app/ru.rzd-2.apk,libraryPath=/data/app-lib/ru.rzd-2]: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:358)
	at java.lang.System.loadLibrary(System.java:526)
	at com.couchbase.touchdb.TDCollateJSON.<clinit>(TDCollateJSON.java:36)
	at com.couchbase.lite.android.AndroidSQLiteStorageEngine.open(AndroidSQLiteStorageEngine.java:46)
	at com.couchbase.lite.Database.open(Database.java:908)
	at com.couchbase.lite.Manager.getDatabase(Manager.java:236)
	at mitaichik.db.couch.Connection.getDatabase(Connection.java:70)
	at mitaichik.db.couch.Connection.getDatabase(Connection.java:84)
	at ru.rzd.poll.repositories.AnswerRepository.findNotSended(AnswerRepository.java:99)
	at ru.rzd.poll.services.SendAnswersService.onStartCommand(SendAnswersService.java:39)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2990)
	at android.app.ActivityThread.access$2200(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5603)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

How i can fix it?

**Comment by hideki** [comment]
Hi @mitaichik

It seems the CBL Android version that you are using does not support your device (CPU) or Android OS version. How do you include CBL Android? And What version of CBL are you using?

If you are using CBL 1.0.2 or 1.0.3 from Android Studio with maven, could you please try to specify compile 'com.couchbase.lite:couchbase-lite-android:1.0.4' instead of compile 'com.couchbase.lite:couchbase-lite-android:1.0.2'  or 1.0.3 in build.gradle?  Please let us know if it works!

Thanks,
Hideki

**Comment by mitaichik** [comment]
Yes, i'm use CBL 1.0.3 from Android Studio. It stacktrace from real project on market place. From different devices (Sony/Samsung/HTC/etc), from different OS version(4.1 - 4.4).  More then 11 thousands users have this error.

Of corse, i try use 1.0.4 version, but i very angry: if you product have limited support of OS version - why you dont say about this on main page?

**Comment by hideki** [comment]
I hope CBL 1.0.4 could solve your problem.

In general,CBL Android supports Android 2.3 Gingerbred (API 9) and above. This is documented in the main page of CBL Android github repository - https://github.com/couchbase/couchbase-lite-android .

At the time we released CBL 1.0.3, Android 5.0 (Lollipop) and new devices which have new architecture were not available. 

From CBL 1.0.4, CBL  Android supports arm640v8a, armeabi-v7a, armeabi, mips, mips64, x86, and x86_64. 

CBL Android is Open-source project and our developer resources are limited. It would be greatly appreciated if you could help CBL Android project.

**Comment by zgramana** [comment]
@mitaichik please also be aware that Android itself has some known issues whereby the required native images are actually present in an APK, but *Android itself* still fails to correctly load them. For more details, please read [the Issue 35962 thread on the AOSP site](https://code.google.com/p/android/issues/detail?id=35962). Please let us know if this appears to be the issue.

**Comment by hideki** [comment]
I will close this ticket. If this is still reproducible, please reopen.
